mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailsView.as_view(), name='details'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.TextField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.TextField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'q_list'

    def get_queryset(self):
        """return the last fivve publications"""
        return Question.objects.order_by("-pub_date")[:5]


class DetailsView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/details.html',
                      {
                          'question': q,
                          'error_message': "you didnt select a choice u sneaki boi"
                      })
    else:
        selected_choice.votes += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question_id, )))


def index(request):
    q_list = Question.objects.order_by('-pub_date')[:5]
    context = {'q_list': q_list}
    return render(request,'polls/index.html', context)


def details(request, question_id):
    # try:
    #     q = Question.objects.get(id=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")

    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': q})


def results(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': q})

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %} <p> {{ error_message }}</p> {% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <ul>
        {% for c in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ c.id }}">
            <label for="choice{{ forloop.counter }}">{{ c.choice_text }}</label>
        {% endfor %}
    </ul>
    <input type="submit" value="vote">
</form>

polls/templates/polls/index.html
{% if q_list %}
    <ul>
        {% for q in q_list %}
            <li><a href="{%  url 'polls:details' q.id %}">{{ q.question_text }} </a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls available</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for c in question.choice_set.all %}
        <li>{{ c.choice_text }} - {{ c.votes }} vote{{ c.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:details' question.id %}">vote again</a>